version: "3"

services:
  # pomodoro-service:
  #   build:
  #     context: ./../pomodoro-service
  #     dockerfile: ./../pomodoro-service/Dockerfile
  #   restart: always
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  postgres:
    image: "postgres:16"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/

  redis:
    image: "redis:8.0.3-alpine"
    restart: always
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
